services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - public
    expose:
      - 8989
    environment:
      - SERVICE_URL_SONARR_8989
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/London
    volumes:
      - config:/config
      - type: volume
        source: media
        target: /tv
        volume:
          subpath: TV-Shows
      - type: volume
        source: media
        target: /downloads
        volume:
          subpath: Downloads
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   placement:
    #     constraints:
    #       - 'node.role == worker'
    #   restart_policy:
    #     condition: on-failure


networks:
  public:
    name: public
    external: true


volumes:
  config:
    name: sonarr
    external: false

  media:
    name: media
    external: true