services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    networks:
      - appbox-net
    expose:
      - 7575


volumes:
  appdata:
    name: appdata-homarr
    external: false


networks:
  appbox-net:
    name: appbox-net
    external: true