services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    restart: unless-stopped
    environment:
      - SECURITY_ENABLELOGIN: true
    expose:
      - 8080
    networks:
      - public
    volumes:
      - configs:/configs


volumes:
  configs:
    name: stirling-pdf
    external: false


networks:
  public:
    name: public
    external: true