services:
  excalidraw:
    restart: unless-stopped
    image: excalidraw/excalidraw:latest
    networks:
      - public
    expose:
      - 80


networks:
  public:
    name: public
    external: true