services:
  excalidraw:
    restart: unless-stopped
    image: excalidraw/excalidraw:latest
    environment:
      - SERVICE_URL_EXCALIDRAW_80
    networks:
      - public
    expose:
      - 80


networks:
  public:
    name: public
    external: true