services:
  excalidraw:
    container_name: excalidraw
    restart: unless-stopped
    image: excalidraw/excalidraw:latest
    networks:
      - appbox-net
    expose:
      - 80
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   placement:
    #     constraints:
    #       - 'node.role == worker'
    #   restart_policy:
    #     condition: on-failure

networks:
  appbox-net:
    external: true