services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    networks:
      - public
    environment:
      DOMAIN: ${VAULTWARDEN_DOMAIN}
    volumes:
      - data:/data/
    expose:
      - 80
      

volumes:
  data:
    name: vaultwarden
    external: false


networks:
  public:
    name: public
    external: true