services:
  sonarr:
    image: linuxserver/sonarr:latest
    environment:
      - SERVICE_FQDN_SONARR_80
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - sonarr-config:/config
      - '/Appbox-Data/Media/TV Shows:/tv:rw'
      - '/Appbox-Data/Media/Downloads:/downloads:rw'
    restart: unless-stopped

volumes:
  sonarr-config:
    name: "sonarr-config"