services:
  syncthing:
    image: 'linuxserver/syncthing:latest'
    environment:
      - SERVICE_FQDN_SYNCTHING_8384
      - PUID=1000
      - PGID=1000
      - 'TZ=Europe/London'
    volumes:
      - 'syncthing-config:/config'
      - '/Appbox-Data/Media/Downloads:/config/data:rw'
    ports:
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:8384/'
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  syncthing-config: null