services:
  iredmail:
    container_name: iredmail
    image: iredmail/mariadb:stable
    hostname: $SERVICE_FQDN_IREDMAIL_HOSTNAME
    environment:
      - HOSTNAME=$SERVICE_FQDN_IREDMAIL_HOSTNAME
      - FIRST_MAIL_DOMAIN=$SERVICE_FQDN_IREDMAIL_MAILDOMAIN
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=$SERVICE_BASE64_IREDMAILADMINPASSWORD
      - MLMMJADMIN_API_TOKEN=$SERVICE_BASE64_MLMMJADMINAPITOKEN
      - ROUNDCUBE_DES_KEY=$SERVICE_BASE64_ROUNDCUBEDESKEY
    ports:
    #  - 80:80
    #  - 443:443
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 25:25
      - 465:465
      - 587:587
    volumes:
      - iredmail_backup-mysql:/var/vmail/backup/mysql
      - iredmail_mailboxes:/var/vmail/vmail1
      - iredmail_mlmmj:/var/vmail/mlmmj
      - iredmail_mlmmj_archive:/var/vmail/mlmmj-archive
      - iredmail_imapsieve_copy:/var/vmail/imapsieve_copy
      - iredmail_custom:/opt/iredmail/custom
      - iredmail_ssl:/opt/iredmail/ssl
      - iredmail_mysql:/var/lib/mysql
      - iredmail_clamav:/var/lib/clamav
      - iredmail_sa_rules:/var/lib/spamassassin
      - iredmail_postfix_queue:/var/spool/postfix


volumes:
  iredmail_backup-mysql:
  iredmail_mailboxes:
  iredmail_mlmmj:
  iredmail_mlmmj_archive:
  iredmail_imapsieve_copy:
  iredmail_custom:
  iredmail_ssl:
  iredmail_mysql:
  iredmail_clamav:
  iredmail_sa_rules:
  iredmail_postfix_queue: