services:
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:8.1
    stdin_open: true
    tty: true
    restart: always
    environment:
     - SERVICE_FQDN_DOCUMENTSERVER_80
     - JWT_ENABLED=true
     - JWT_SECRET=$SERVICE_BASE64_DOCUMENTSERVER
     - JWT_HEADER=AuthorizationJwt
    expose:
     - '80'
     - '443'
    volumes:
     - document-data:/var/www/onlyoffice/Data
     - document-forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
     - /var/log/onlyoffice:/var/log/onlyoffice:rw
     - /Appbox-Data/Media/Fonts:/usr/share/fonts/truetype/custom

volumes:
  document-data:
    name: "document-data"
  document-forgotten:
    name: "document-forgotten"