services:
  mysql:
    container_name: onlyoffice-mail-mysql-server
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_USER=$SERVICE_USER_MYSQLROOT
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_MYSQLROOT
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

  onlyoffice-mail-server:
    container_name: onlyoffice-mail-server
    image: onlyoffice/mailserver:1.6.75
    depends_on:
      - mysql
    hostname: ${SERVICE_FQDN_MAILSERVER}
    environment:
      - SERVICE_FQDN_MAILSERVER_8081
      - MYSQL_SERVER=onlyoffice-mail-mysql-server
      - MYSQL_SERVER_PORT=3306
      - MYSQL_ROOT_USER=$SERVICE_USER_MYSQLROOT
      - MYSQL_ROOT_PASSWD=$SERVICE_PASSWORD_MYSQLROOT
      - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
    restart: always
    privileged: true
    ports: ['25:25','143:143','587:587']
    stdin_open: true
    tty: true
    expose:
      - '8081'
      - '3306'
    volumes:
      - mail-data:/var/vmail
      - mail-certs:/etc/pki/tls/mailserver
      - mail-log:/var/log

  onlyoffice-mail-server:
    container_name: onlyoffice-mail-server
    image: onlyoffice/mailserver:1.6.75
    depends_on:
      - mysql
    hostname: onlyoffice-mail-server
    environment:
      - SERVICE_FQDN_MAILSERVER_8081
      - MYSQL_SERVER=onlyoffice-mysql-server
      - MYSQL_SERVER_PORT=3306
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWD=$SERVICE_PASSWORD_MYSQLROOT
      - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
    restart: always
    privileged: true
    ports: ['25:25','143:143','587:587']
    stdin_open: true
    tty: true
    expose:
      - '8081'
      - '3306'
    volumes:
      - mail-data:/var/vmail
      - mail-certs:/etc/pki/tls/mailserver
      - mail-log:/var/log


volumes:
  mail-data:
    name: "onlyoffice-mailserver-data"
  mail-certs:
    name: "onlyoffice-mailserver-certs"
  mysql-data:
    name: "onlyoffice-mailserver-mysql-data"