services:
  syncthing:
    image: 'linuxserver/syncthing:latest'
    environment:
      - SERVICE_FQDN_SYNCTHING_8384
      - PUID=1000
      - PGID=1000
      - 'TZ=${TZ:-Etc/UTC}'
    volumes:
      - 'syncthing-config:/config'
      - '/Appbox-Data/SyncDownloads:/config/data:rw'
    ports:
      - '22000:22000/tcp'
      - '22000:22000/udp'
      - '21027:21027/udp'

volumes:
  syncthing-config: null