services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    user: 1000:1000
    expose:
      - 8096
    networks:
      - public
    volumes:
      - config:/config
      - cache:/cache
      - media:/media
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   placement:
    #     constraints:
    #       - 'node.role == worker'
    #   restart_policy:
    #     condition: on-failure

networks:
  public:
    name: public
    external: true


volumes:
  config:
    name: jellyfin-config
    external: false

  cache:
    name: jellyfin-cache
    external: false

  media:
    name: media
    external: true
