services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    expose:
      - 53 # DNS
      - 80 # Web
      - 443 # Web
      - 67 # DHCP Server
      - 123 # NPT Servre
    environment:
      - SERVICE_URL_LIDARR_8686
      - TZ=Europe/London
      - FTLCONF_webserver_api_password=$SERVICE_PASSWORD_PIHOLE
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      - FTLCONF_dns_listeningMode=ALL
    networks:
      - public
    volumes:
      - pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE


volumes:
  pihole:
    name: "pi-hole"


networks:
  public:
    name: public
    external: true