services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - appbox-net
    expose:
      - 7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - config:/config
      - type: volume
        source: media
        target: /movies
        volume:
          subpath: Movies
      - type: volume
        source: media
        target: /downloads
        volume:
          subpath: Downloads
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   placement:
    #     constraints:
    #       - 'node.role == worker'
    #   restart_policy:
    #     condition: on-failure


networks:
  appbox-net:
    name: appbox-net
    external: true
    

volumes:
  config:
    name: lidarr-config
    external: false

  media:
    name: media
    external: true