services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - public
    expose:
      - 7878
    environment:
      - USER_UID={{environment.USER_ID}}
      - USER_GID={{environment.GROUP_ID}}
      - TZ={{environment.TZ}}
    volumes:
      - config:/config
      - type: volume
        source: media
        target: /movies
        volume:
          subpath: Movies
      - type: volume
        source: media
        target: /downloads
        volume:
          subpath: Downloads


networks:
  public:
    name: public
    external: true
    

volumes:
  config:
    name: radarr
    external: false

  media:
    name: media
    external: true