services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      - public
    expose:
      - 7878
    environment:
      - SERVICE_FQDN_RADARR_7878
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/London
    volumes:
      - config:/config
      - type: volume
        source: media
        target: /movies
        volume:
          subpath: Movies
      - type: volume
        source: media
        target: /downloads
        volume:
          subpath: Downloads


networks:
  public:
    name: public
    external: true
    

volumes:
  config:
    name: radarr
    external: false

  media:
    name: media
    external: true