services:
  lidarr:
    restart: unless-stopped
    image: lscr.io/linuxserver/lidarr:latest
    expose:
      - 8686
    networks:
      - public
    environment:
      - USER_UID={{environment.USER_ID}}
      - USER_GID={{environment.GROUP_ID}}
      - TZ={{environment.TZ}}
    volumes:
      - config:/config
      - type: volume
        source: media
        target: /music
        volume:
          subpath: Music
      - type: volume
        source: media
        target: /downloads
        volume:
          subpath: Downloads


networks:
  public:
    name: public
    external: true


volumes:
  config:
    name: lidarr
    external: false

  media:
    name: media
    external: true