services:
  filebrowser:
    image: gtstef/filebrowser:stable
    restart: unless-stopped
    networks:
      - public
    volumes:
      - media:/folder
      - data:/home/filebrowser/data
    expose:
      - 80


networks:
  public:
    name: public
    external: true


volumes:
  media:
    name: media
    external: true

  data:
    name: filebrowser
    external: false