# Ports:
# 139
# 445

services:
  samba:
    image: dperson/samba
    ports:
      - 139:139
    volumes:
      - /Appbox-Data/Media:/mount
    command: -p -u "${SERVICE_USER_SAMBA};${SERVICE_PASSWORD_SAMBA}"
    stdin_open: true
    tty: true