services:

  iredmail:
    extends:
      file: ../Apps/compose.iredmail.yml
      service: iredmail
      
  environment:
    - SERVICE_FQDN_IREDMAIL_HOSTNAME
    - SERVICE_FQDN_IREDMAIL_MAILDOMAIN
    - SERVICE_BASE64_IREDMAIL_ADMIN_PASSWORD
    - SERVICE_BASE64_MLMMJADMIN_API_TOKEN