services:

  iredmail:
    extends:
      file: ../Apps/compose.iredmail.yml
      service: iredmail

    environment:
      - HOSTNAME=$SERVICE_FQDN_IREDMAIL_HOSTNAME
      - FIRST_MAIL_DOMAIN=$SERVICE_FQDN_IREDMAIL_MAILDOMAIN
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=$SERVICE_BASE64_IREDMAILADMINPASSWORD
      - MLMMJADMIN_API_TOKEN=$SERVICE_BASE64_MLMMJADMINAPITOKEN
      - ROUNDCUBE_DES_KEY=$SERVICE_BASE64_ROUNDCUBEDESKEY