services:
  lidarr:
    restart: unless-stopped
    image: lscr.io/linuxserver/lidarr:latest
    expose:
      - 8686
    networks:
      - public
    environment:
      - SERVICE_URL_LIDARR_8686
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/London
    volumes:
      - config:/config
      - type: volume
        source: media
        target: /music
        volume:
          subpath: Music
      - type: volume
        source: media
        target: /downloads
        volume:
          subpath: Downloads


networks:
  public:
    name: public
    external: true


volumes:
  config:
    name: lidarr
    external: false

  media:
    name: media
    external: true