services:
  drawio:
    image: jgraph/drawio
    restart: unless-stopped
    environment:
      - SERVICE_URL_DRAWIO_80
    networks:
      - public
    expose:
      - 8080


networks:
  public:
    name: public
    external: true