services:
  stirling-pdf:
    image: 'stirlingtools/stirling-pdf:latest'
    volumes:
      - stirling-training-data:/usr/share/tesseract-ocr/5/tessdata
      - stirling-configs:/configs
      - stirling-custom-files:/customFiles/
      - stirling-logs:/logs/
    environment:
      - SERVICE_FQDN_SPDF_80
      - DOCKER_ENABLE_SECURITY=false

volumes:
  stirling-training-data: 
    name: "stirling-training-data"
  stirling-configs:
    name: "stirling-configs"
  stirling-custom-files:
    name: "stirling-custom-files"
  stirling-logs:
    name: "stirling-logs"