# Inject tempory SQL from env args
echo "-- NOTE: This SQL file is generated by script at start. Do not make changes as they will be overwritten!

CREATE DATABASE IF NOT EXISTS onlyoffice CHARACTER SET "utf8" COLLATE "utf8_general_ci";
CREATE DATABASE IF NOT EXISTS onlyoffice_mailserver CHARACTER SET "utf8" COLLATE "utf8_general_ci";

CREATE USER 'onlyoffice_root'@'localhost' IDENTIFIED BY '$SERVICE_PASSWORD_DBROOTUSER';
CREATE USER 'onlyoffice_user'@'localhost' IDENTIFIED BY '$SERVICE_PASSWORD_DBUSER';

GRANT ALL PRIVILEGES ON * . * TO 'onlyoffice_root'@'%' IDENTIFIED BY '$SERVICE_PASSWORD_DBROOTUSER';
GRANT ALL PRIVILEGES ON * . * TO 'onlyoffice_user'@'%' IDENTIFIED BY '$SERVICE_PASSWORD_DBUSER';

FLUSH PRIVILEGES;" > ./init.sql