# Inject tempory SQL from env args
echo "Generating SQL"

echo "-- NOTE: This SQL file is generated by script at start. Do not make changes as they will be overwritten!

CREATE DATABASE IF NOT EXISTS onlyoffice CHARACTER SET "utf8" COLLATE "utf8_general_ci";
CREATE DATABASE IF NOT EXISTS onlyoffice_mailserver CHARACTER SET "utf8" COLLATE "utf8_general_ci";

CREATE USER 'onlyoffice_root'@'localhost' IDENTIFIED BY '$ONLYOFFICE_DB_ROOT_USER';
CREATE USER 'onlyoffice_user'@'localhost' IDENTIFIED BY '$ONLYOFFICE_DB_USER';
CREATE USER 'onlyoffice_user_mail'@'localhost' IDENTIFIED BY '$ONLYOFFICE_DB_USER_MAIL';

GRANT ALL PRIVILEGES ON * . * TO 'onlyoffice_root'@'%' IDENTIFIED BY '$ONLYOFFICE_DB_ROOT_USER';
GRANT ALL PRIVILEGES ON * . * TO 'onlyoffice_user'@'%' IDENTIFIED BY '$ONLYOFFICE_DB_USER';
GRANT ALL PRIVILEGES ON * . * TO 'onlyoffice_user_mail'@'%' IDENTIFIED BY '$ONLYOFFICE_DB_USER_MAIL';

FLUSH PRIVILEGES;" > ./1-init.sql