services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    environment:
      - SERVICE_FQDN_JDOWNLOADER2_5800
    volumes:
      - jdownloader2-config:/config:rw
      - /Appbox-Data/Media/Downloads:/output:rw

volumes:
  jdownloader2-config: null