services:
  gitea:
    image: docker.gitea.com/gitea:1.25.5
    restart: unless-stopped
    environment:
      - USER_UID={{environment.USER_ID}}
      - USER_GID={{environment.GROUP_ID}}
    networks:
      - public
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000
    ports:
      - 23:22


volumes:
  data:
    name: gitea
    external: false


networks:
  public:
    name: public
    external: true